module.exports = {
  url: "http://192.168.127.55:8080",
  client: "http://localhost:3000",
  gray: "gray",
  yellow: "yellow",
  orange: "orange",
  red: "red",
  transparent: "",
  admin: "Admin",
  quanLy: "Quản lý",
  cskh: "CSKH",
  sale: "Sale",
  dangGiaoDich: "Đang giao dịch",
  ngungGiaoDich: "Ngừng giao dịch",
  dangLamViec: "Đang làm việc",
  daNghiLam: "Đã nghỉ làm",
};
