module.exports = {
  url: "https://api.connecthome.vn",
  client: "https://connecthome.vn",
  gray: "gray",
  yellow: "yellow",
  orange: "orange",
  red: "red",
  transparent: "",
  admin: "Admin",
  quanLy: "Quản lý",
  cskh: "CSKH",
  sale: "Sale",
  dangGiaoDich: "Đang giao dịch",
  ngungGiaoDich: "Ngừng giao dịch",
  dangLamViec: "Đang làm việc",
  daNghiLam: "Đã nghỉ làm",
  giaBanTangDan: "Giá bán tăng dần",
  giaBanGiamDan: "Giá bán giảm dần",
  giaThueTangDan: "Giá thuê tăng dần",
  giaThueGiamDan: "Giá thuê giảm dần",
};
